version: "3"
services:
  web:
    build: .
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    environment:
      RAILS_ENV: development 
